### ISSUE TITLE
Contact Page 📞

### ISSUE THREAD

**Issue by Lakhankumawat** [pushpakumari5117/pushpaPortfolio#4]
![contactpage](https://user-images.githubusercontent.com/55774240/114339137-225c8d80-9b72-11eb-8a77-e2460e9812d5.png)

As you can see contact page does not seems to be Responsive on mobile devices resolution.

**Comment by pushpakumari5117** [comment]
Hey! Thanks for the review.... But I fixed this page few days back.
You can see the image below...
Can you please again refresh the page and let me know...

[image: contactpage]
<https://user-images.githubusercontent.com/55774240/114339137-225c8d80-9b72-11eb-8a77-e2460e9812d5.png>

**Comment by Lakhankumawat** [comment]
Nope Now also i Checked it seems the issue remains You may check it here [PortFolio](https://pushpakumari5117.github.io/pushpaPortfolio/#contact)

**Comment by pushpakumari5117** [comment]
It's showing me this....
